### ISSUE TITLE
Handle timezones better

### ISSUE THREAD

**Issue by reyjrar** [reyjrar/Parse-Syslog-Line#11]
Perhaps something like this:

``` perl
$Parse::Syslog::Line::SetTimeZone = "UTC";
```

Which would cause the returned hash to have:

``` perl
{
   ...
   datetime_str => 'YYYY-MM-DD HH:MM:SS(-|+)ZZZZ',
}
```

The idea is even if the system isn't logging in UTC, it could be normalized to UTC by this module.  This might also be helpful if local datacenters have local timezones, the messages can be parsed locally, converted to a common or standard timezone and then fed into a central system from there.

**Comment by StarLightPL** [comment]
on it.
