### ISSUE TITLE
add or change one field to include the timestamp in ISO8601 format

### ISSUE THREAD

**Issue by abraxxa** [reyjrar/Parse-Syslog-Line#7]
This would make storing the messages in Elasticsearch easier as it requires timestamps in ISO8601 format.

**Comment by ttyS4** [comment]
Hmm, and where does strftime_epoch comes from?
Maybe it is just me, but I cannot find it.

**Comment by reyjrar** [comment]
This has been in the library for a while now, including the ability to control the timezones.
